[package]
name = "rdiff"
version = "0.1.0"
authors = ["lwl <lwl@xkool.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
clap = "2.33.3"